spring:
  application:
    name: ordini-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ordini
    username: skikky
    password: stickStick
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8083

application:    #vedi come si fa un gateway
  config:
    utenti-url: http://localhost:8052/api/v1/utente
    prodotti-url: http://localhost:8050/api/v1/prodotto